#!/bin/sh

clock=$(date '+%I')

case "$clock" in
	"00"|"12") icon="🕛" ;;
	"01"|"13") icon="🕐" ;;
	"02"|"14") icon="🕑" ;;
	"03"|"15") icon="🕒" ;;
	"04"|"16") icon="🕓" ;;
	"05"|"17") icon="🕔" ;;
	"06"|"18") icon="🕕" ;;
	"07"|"19") icon="🕖" ;;
	"08"|"20") icon="🕗" ;;
	"09"|"21") icon="🕘" ;;
	"10"|"22") icon="🕙" ;;
	"11"|"23") icon="🕚" ;;
esac

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal)" ;;
esac

date "+%d.%m. $icon %H:%M"