#!/bin/sh

sink="alsa_output.pci-0000_00_1f.3.analog-stereo"

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer --sink "$sink" -t ;;
	4) pamixer --sink "$sink" --allow-boost -i 1 ;;
	5) pamixer --sink "$sink" --allow-boost -d 1 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --sink "$sink" --get-mute) = true ] && echo "🔇 " && exit

vol="$(pamixer --sink "$sink" --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon $vol%"
